// Run with Playwright available via NODE_PATH. Saves review screenshots and checks.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const out = path.resolve(__dirname, '../qa');
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  const checks = [];
  await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
  await page.screenshot({ path: path.join(out, 'desktop-hero.png') });
  for (let y = 0; y < await page.evaluate(() => document.body.scrollHeight); y += 700) {
    await page.evaluate(y => window.scrollTo({ top: y, behavior: 'instant' }), y);
    await page.waitForTimeout(130);
  }
  await page.waitForTimeout(900);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: path.join(out, 'desktop-full.png'), fullPage: true });
  const missing = await page.locator('img').evaluateAll(imgs => imgs.filter(img => !img.complete || !img.naturalWidth).map(img => img.src));
  assert.deepEqual(missing, []); checks.push('All research images load');
  const resources = await page.locator('[src],link[href],a[href]').evaluateAll(nodes => [...new Set(nodes.map(n => n.getAttribute('src') || n.getAttribute('href')).filter(x => x && !/^(https?:|#|mailto:)/.test(x)))]);
  for (const url of resources) assert.equal((await context.request.get('http://127.0.0.1:4173/' + url)).status(), 200, url);
  checks.push('All local links and assets return HTTP 200, including PDF');
  for (const button of await page.locator('[data-figure]').all()) {
    await button.click();
    assert.equal(await page.locator('#figure-dialog').evaluate(d => d.open), true);
    assert.ok(await page.locator('#lightbox-image').evaluate(img => img.complete && img.naturalWidth > 0));
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => !document.querySelector('#figure-dialog').open && !document.body.classList.contains('modal-open'));
    assert.equal(await page.locator('#figure-dialog').evaluate(d => d.open), false);
    assert.equal(await page.locator('body').evaluate(b => b.classList.contains('modal-open')), false);
  }
  checks.push('All six figure viewers open, close with Escape, and restore page scrolling');
  await page.locator('[data-figure="overview"]').click();
  await page.keyboard.press('ArrowLeft');
  assert.match(await page.locator('#lightbox-title').textContent(), /Three paths/);
  await page.keyboard.press('ArrowRight');
  assert.match(await page.locator('#lightbox-title').textContent(), /Adaptive/);
  await page.locator('.lightbox-close').click();
  checks.push('Figure navigation wraps in both directions');
  await page.locator('#tab-observe').click();
  assert.equal(await page.locator('#state-panel').getAttribute('data-current'), 'observe');
  assert.equal(await page.locator('#demo-assistant').evaluate(el => getComputedStyle(el).opacity), '1');
  await page.locator('#tab-withdraw').click();
  await page.locator('#cancel-fade').click();
  assert.equal(await page.locator('#state-panel').getAttribute('data-current'), 'stay');
  await page.waitForTimeout(3100);
  assert.equal(await page.locator('#restore-ai').isVisible(), false);
  await page.locator('#tab-withdraw').click();
  await page.locator('#restore-ai').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#demo-assistant').evaluate(el => Number(getComputedStyle(el).opacity)), 0);
  await page.screenshot({ path: path.join(out, 'withdrawal-demo.png') });
  await page.locator('#restore-ai').click();
  assert.equal(await page.locator('#state-panel').getAttribute('data-current'), 'stay');
  await page.locator('#tab-stay').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#tab-observe').getAttribute('aria-selected'), 'true');
  checks.push('State tabs, unchanged Observe sidebar, cancellation, fade completion, re-entry, and keyboard controls work');
  await page.locator('.abstract summary').click();
  assert.equal(await page.locator('.abstract').evaluate(d => d.open), true);
  await page.locator('.abstract summary').click();
  await page.locator('.citation summary').click();
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.locator('#copy-citation').click();
  assert.match(await page.locator('#copy-status').textContent(), /copied/);
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /drawbreath2027/);
  checks.push('Abstract disclosure and citation clipboard copy work');
  await page.locator('.citation summary').click();
  const bounds = [];
  for (const width of [1440, 1024, 768, 760, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.waitForTimeout(120);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflow, false, `Horizontal overflow at ${width}px`);
    bounds.push(width);
  }
  checks.push('No horizontal overflow at widths ' + bounds.join(', '));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: path.join(out, 'mobile-hero.png') });
  await page.screenshot({ path: path.join(out, 'mobile-full.png'), fullPage: true });
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'true');
  await page.locator('.nav-links a[href="#gallery"]').click();
  assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
  checks.push('Mobile menu opens and closes after navigation');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.locator('.reveal').first().evaluate(el => getComputedStyle(el).opacity), '1');
  await page.locator('#tab-withdraw').click();
  await page.locator('#restore-ai').waitFor({ state: 'visible' });
  checks.push('Reduced-motion mode keeps content visible and the demo functional');
  const nojs = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 1440, height: 900 } });
  const staticPage = await nojs.newPage();
  await staticPage.goto('http://127.0.0.1:4173');
  assert.equal(await staticPage.locator('.reveal').first().evaluate(el => getComputedStyle(el).opacity), '1');
  checks.push('Research content and PDF links remain available without JavaScript');
  assert.deepEqual(errors, []);
  checks.push('No browser JavaScript errors or HTTP failures');
  fs.writeFileSync(path.join(out, 'checks.json'), JSON.stringify({ checkedAt: new Date().toISOString(), checks, errors }, null, 2));
  console.log(JSON.stringify({ checks, errors }, null, 2));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
